### ------------------------------------------------------------------------------------------------------------

### 17/12/25 - ©Fabio Benedetti (Plant Ecology group, IPS, Uni Bern)

### R script to compute droughts based on the Standardised Precipitation-Evapotranspiration Index (SPEI) for different 
### quantile mapping (QM) strategies. Re-use Script#7.1.2 used to compute scPDSI

### The Standardized Precipitation–Evapotranspiration Index (SPEI) is a climate drought index that quantifies anomalies
### in climatic water balance, defined as: D = P - PET
### SPEI measures how unusually dry or wet conditions are relative to the local historical climate,
### accounting for both water supply and atmospheric demand.

### SPEI is constructed (conceptually) through:
# - Climatic water balance through monthly (or aggregated) precipitation is combined with estimated PET to compute 𝑃−𝑃𝐸𝑇
# - Accumulation over a chosen timescale: The water balance is accumulated over a user-defined window 
# (e.g. 1, 3, 6, 12 months), allowing SPEI to represent drought processes operating at different temporal scales.
# - Standardization: The accumulated series is fitted to a probability distribution (commonly log-logistic) and
# transformed into standardized units (mean = 0, SD = 1).
# - Interpretation: 
#Interpretation guidelines
#   SPEI value      Interpretation
#   0	            Normal
#   −1	            Moderate drought
#   −1.5	        Severe drought
#   −2 or lower	    Extreme drought
#   +1	            Moderately wet
#   +2	            Extremely wet

### -> Because it is standardized, SPEI values are comparable across regions and climates.

### What SPEI is not good at:
# - Does not represent actual soil moisture
# - Does not directly measure plant water status
# - Is not an observation, but a climate-derived indicator

### What is scPDSI NOT good for:
# - Not good for short-term droughts: Poor sensitivity to: Flash droughts, agricultural drought at weekly scales,
# too much “memory”
# - Not good for impact-specific questions as it does not directly represent: Root-zone soil moisture, crop stress,
# Ecosystem functioning, Vegetation response may lag or decouple
# - Fixed soil parameters; Soil water capacity is simplified, often poorly constrained, and no dynamic rooting depth or land cover change
# - Not event-based so cannot clearly isolate: Onset timing, Termination timing & poor for attribution of single drought events

### Avoid scPDSI if:
# - You care about weekly–monthly agricultural impacts
# - You want explicit timescale control
# - You are modeling ecosystem or crop responses
# - You need process realism in evapotranspiration
# - You want to link drought to plant traits, biomass, or resistance metrics! 

### In short: use scPDSI to describe background climatic dryness; use SPI/SPEI to describe event timing and scale
### -> We need to estimate SPEI based on the our long-term climate reconstructions and compare them 

### R script to: 
###  - Load the TS of daily total precipitation and daily maximum temperature generated by different quantiles 
###    and QM strategies ('global','monthly','anoms' and 'mw')
###  - Use the 'SPEI' and 'scPDSI' R packages to compute the scPDSI on a monthly scale from 1950 and onwards
###  - Make tempral heatmaps to analyze how droughts identified by the SPEI features and temporal dynamics 
###    are affected by these parameters
### - Compare to scPDSI dynamics

### Last update: 09/07/26 (Re-computing monthly SPEI over the full reconstruction period for the forests)

### ------------------------------------------------------------------------------------------------------------

# Libraries 
library("dplyr")
library("ggplot2")
library("tibble")
library("data.table")
library("zoo")
library("reshape2")
require("scales")
library("lubridate")
library("parallel")
library("SPEI")
# install.packages("https://cran.r-project.org/src/contrib/Archive/scPDSI/scPDSI_0.1.3.tar.gz", repo = NULL, type = "source")
library("scPDSI")

# Dir. where to store ECEs tables and SPEI values
extremes_dir <- "/home/fbenedetti/ERA5-Land-DEU-processed/daily/quantile_mapping_outputs/ECEs_tables"

### ------------------------------------------------------------------------------------------------------------

### Re-use the code from Script#7.1 & #2.3.1 to compute scPDSI for every EP based on bias-corrected E-OBS data

# To test master FUN while you are writing it
# system = "forests"
# region = "HND"
# method = "mw"

compute_SPEI <- function(system, region, method, min_age = 10) {

        #' This function takes four arguments and returns a formatted data.frame:
        #' @param system System name (character): 'grasslands' or 'forests'
        #' @param region Region name (character): 'SCH' or 'HND' or 'SWA'
        #' @param method Which quantile mapping approach to run (character): 'global' or 'monthly' or 'mw' or 'anomalies'
        #' @param min_age Age below which forets data should not be taken into account because StandAge is outside of GAMM
        #' traning range (10-40 years old) (integer) - Default == 10 because youngest stands fit into the GAMMs are 12 yo
        #' @return A formatted data.frame combining the DSM data
        
        ## Message
        message(paste("\nComputing SPEI for the ",system," of the ",region," based on the ",method," QM strategy\n", sep = ""))
        if( system == "forests" ) {
            setwd("/home/fbenedetti/ERA5-Land-DEU-processed/daily/quantile_mapping_outputs/combined_time_series_full/forests")
        } else {
            setwd("/home/fbenedetti/ERA5-Land-DEU-processed/daily/quantile_mapping_outputs/combined_time_series_full/grasslands")
        } # eo if else loop - directories

        ## Loading daily Ta_200 & total precip.
        if( system == "forests" ) {
            setwd("/home/fbenedetti/ERA5-Land-DEU-processed/daily/quantile_mapping_outputs/combined_time_series_full/forests")
            d_temp <- readRDS(paste("table_combined_obs+corr_max_Ta_200_",system,"_",region,".rds", sep = ""))
            d_precip <- get(load(paste("table_combined_obs+corr_",method,"_total_precipitation_",system,"_",region,".Rdata", sep = "")))
        } else {
            d_temp <- get(load(paste("table_combined_obs+corr_",method,"_max_Ta_200_",system,"_",region,".Rdata", sep = "")))
            d_precip <- get(load(paste("table_combined_obs+corr_",method,"_total_precipitation_",system,"_",region,".Rdata", sep = "")))
        } # eo if else loop - directories

        ## In a mclappy, compute DSL at EP-level
        require("parallel")
        
        list_SPEI <- mclapply(X = unique(d_temp$EP),
        
            FUN = function(p) {
                # For testing:
                # p <- unique(d_temp$EP)[13]; p

                # Subset EP
                message(paste("Computing SPEI for ",p,sep = ""))
                sub_d_temp <- d_temp[d_temp$EP == p,]
                sub_d_precip <- d_precip[d_precip$EP == p,]

                # Add D/M/Y based on 'Date'
                sub_d_temp$DOY <- lubridate::yday(sub_d_temp$Date)
                sub_d_temp$month <- lubridate::month(sub_d_temp$Date)
                sub_d_temp$year <- lubridate::year(sub_d_temp$Date)

                # Adjust colnames before merging
                if( system == "grasslands" ) {
                    colnames(sub_d_temp)[5] <- "temperature"
                } else {
                    colnames(sub_d_temp)[6] <- "temperature"
                }
                # For precip. too
                colnames(sub_d_precip)[5] <- "precipitation"
                
                # Merge
                sub_d_temp <- sub_d_temp %>% left_join(sub_d_precip %>% select(EP, Date, precipitation), by = c("EP","Date"))
                # summary(sub_d_temp) # OK

                ### 09/07/26: Add a minimum age requirement for forests based on 'min_age' argument
                ### -> Discard values for stands that show a stand age < min_age 
                if( system == "forests" ) {
                    if( sum(unique(sub_d_temp$Stand_age) < min_age ) > 0 ) {
                        sub_d_temp <- sub_d_temp[sub_d_temp$Stand_age >= min_age ,]
                    } # eo if else loop - min_age
                } # eo if else loop - forests

                # Need to aggregate to the monthly scale as SPEI operates on monthly time step
                sub_d_temp$m <- floor_date(sub_d_temp$Date, "month") # summary(sub_d_temp$m)

                d_mon <- sub_d_temp %>%
                    group_by(m) %>%
                    summarize(
                        precip = sum(precipitation, na.rm = TRUE),
                        temp = mean(temperature, na.rm = TRUE)
                    ) # eo summarize
                # summary(data.frame(d_mon))

                # Pick latitude value based on 'region'
                if(region == "SCH") {
                    lat <- 53
                } else if(region == "HND") {
                    lat <- 51.15
                } else if(region == "SWA") {
                    lat <- 48.45
                } # eo if else loop - region

                # Compute PE using the Thornthwaite equation ('SPEI' package)
                d_mon$PE <- SPEI::thornthwaite(Tave = d_mon$temp, lat = lat)
                # Compute climatic water balance (WB = P − PET)
                d_mon$WB <- (d_mon$precip) - (d_mon$PE)
                # summary(d_mon)

                ### Compute SPEI at different time scales: 3/6/12 months
                # SPEI-3 (short-term stress / resistance)
                spei_3 <- spei(d_mon$WB, scale = 3)
                # SPEI-6 (seasonal biomass response)
                spei_6 <- spei(d_mon$WB, scale = 6)
                # SPEI-12 (legacy effects / recovery)
                spei_12 <- spei(d_mon$WB, scale = 12)
                
                # Add SPEI values to 'd_mon' as different columns
                d_mon$SPEI3 <- spei_3$fitted
                d_mon$SPEI6 <- spei_6$fitted
                d_mon$SPEI12 <- spei_12$fitted
                # summary(d_mon)

                # Add EP ID
                d_mon <- d_mon %>% add_column(EP = p, .before = 1)

                # Clean and return
                rm(spei_3,spei_6,spei_12,sub_d_temp,sub_d_precip)
                gc()
                
                return(d_mon)

            } # eo FUN - EPs
            ,
            mc.cores = 20

        ) # eo mclapply - list_SPEI

        ## Rbind
        t_SPEI <- dplyr::bind_rows(list_SPEI)
        # dim(t_SPEI) ; summary(t_SPEI) ; head(data.frame(t_SPEI))
        rm(list_SPEI); gc()
        
        ## Add metadata
        t_SPEI <- t_SPEI %>% add_column(region = region, .before = 3)
        t_SPEI <- t_SPEI %>% add_column(qm_method = method, .before = 4)
        t_SPEI <- t_SPEI %>% add_column(System = system, .before = 1)

        ## And save in proper dir
        if( exists("t_SPEI") == FALSE ) {
            stop(
              paste("!!! ERROR: Could not find the final SPEI table for the ",system," of the ",region," based on the ",method," QM strategy\n", sep = "")
            )
        } else {
            setwd(extremes_dir)
            paste("Saving the SPEI table for the ",system," of the ",region," based on the ",method," QM strategy\n", sep = "")
            save(x = t_SPEI, file = paste("table_SPEI_",system,"_",region,"_",method,".Rdata", sep = "") )
        } # eo if else loop

} # eo FUN - compute_SPEI

### Apply compute_scPDSI() to all regions and based on all bias correction stategies

### 09/07/26: Re-computing monthly SPEI over the full reconstruction period for the forests using a min_age cap of 10 yo

for(r in c("HND","SCH","SWA")) {
    for(m in c("global","monthly","mw","anomalies")) {
        compute_SPEI(system = "forests", region = r, method = m) # eo compute_SPEI
    } # eo for loop - m
} # eo for loop - r


### ------------------------------------------------------------------------------------------------------------

### 05/01/26: Plotting the SPEI values computed above for the 'mw' QM strategy and for all three timescales (3/6/12 months)
### through heatmaps - follow the colorpalette used for the BES 2025 poster

setwd(extremes_dir) # dir()[grep("SPEI",dir())] # there should be 3x4x2 -> 24 files

### Load all files and make one panel of 12 Plots: 4 rows (QM) x 3 columns (regions)
files <- dir()[grep("SPEI",dir())]
files <- files[grep("forests",files)]
files <- files[grep("_mw",files)] # files
res <- lapply(files, function(f) { d <- get(load(f)); return(d) })
ddf <- dplyr::bind_rows(res)
rm(res); gc()
# summary(ddf); head(ddf)
# unique(ddf$EP); length(unique(ddf$EP)) # 124 EPs for the forests, 26 EPs were dropped

### Define the breakpoints and labels for the divergent color palette (% anomalies to the mean)
# https://www.google.com/search?q=spei+drought+categories&sca_esv=2bc7513dd8de01bf&udm=2&biw=1440&bih=728&sxsrf=AE3TifOon0DPZj18h6Pu1FrCA5jeU5ktyA%3A1767628843450&ei=K-BbaauTG7Kyi-gPw9-CuAw&ved=0ahUKEwjr1LvK4vSRAxUy2QIHHcOvAMcQ4dUDCBI&uact=5&oq=spei+drought+categories&gs_lp=Egtnd3Mtd2l6LWltZyIXc3BlaSBkcm91Z2h0IGNhdGVnb3JpZXMyBBAAGB5I1xxQ4wRY7xpwA3gAkAEAmAF7oAHaAqoBAzQuMbgBA8gBAPgBAfgBApgCCKACgAPCAgYQABgIGB7CAgYQABgHGB7CAggQABgHGAgYHsICBhAAGAUYHsICCBAAGAUYBxgewgIFEAAYgASYAwCIBgGSBwM3LjGgB-AHsgcDNC4xuAfxAsIHBTAuNS4zyAcZgAgA&sclient=gws-wiz-img#sv=CAMSVhoyKhBlLUxXNlVfT3VpaDZEVWtNMg5MVzZVX091aWg2RFVrTToOQ0xUV2ZUMFQ3S0FPZU0gBCocCgZtb3NhaWMSEGUtTFc2VV9PdWloNkRVa00YADABGAcgtKr5ITACSgoIAhACGAIgAigC

#   SPEI values     Interpretation
#   > 2	            Extremely Wet
#   1.5 to 2        Severely Wet
#   1 to 1.5        Moderately Wet
#   0.5 to 1        Mildly Wet
#   -0.5 to 0.5     Normal
#   -0.5 to -1      Mild Drought
#   -1 to -1.5      Moderate Drought
#   -1.5 to -2      Severe Drought
#   < -2            Extreme Drought

### Define scPDSI bins for a nice looking and adequate colorbar
breaks <- c(-3,-2,-1.5,-1,-0.5,0.5,1,1.5,2,3) # breaks
# Give it it adequate labels too
labels <- c("< -2","-2 to -1.5","-1.5 to -1","-1 to -0.5","-0.5 to 0.5","0.5 to 1","1 to 1.5","1.5 to 2","> 2")
# Add bins to 'ddf'
ddf <- ddf %>% mutate(SPEI3_bin = cut(SPEI3, breaks = breaks, labels = labels, include.lowest = T))
ddf <- ddf %>% mutate(SPEI6_bin = cut(SPEI6, breaks = breaks, labels = labels, include.lowest = T))
ddf <- ddf %>% mutate(SPEI12_bin = cut(SPEI12, breaks = breaks, labels = labels, include.lowest = T))

# Re-order levels of the 'region' factor as follows: SCH > HND > SWA
ddf$region <- factor(ddf$region, levels = c("SCH","HND","SWA"))

heat <- ggplot() + geom_tile(aes(y = factor(EP), x = m, fill = SPEI3_bin), data = ddf) + 
    scale_fill_brewer(name = "SPEI", na.value = 'grey75', palette = "RdYlGn", direction = 1) + 
    theme_grey(base_size = 10) + scale_x_date(date_breaks = "1 year", date_labels = "%Y",
        limits = c(min(ddf$m),max(ddf$m)), expand = c(0,0)) +
    xlab("Time") + ylab("EPs") + theme(axis.text.y = element_blank(),
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1, size = 4)) + 
    facet_wrap(factor(region)~., scales = "free_y", nrow = 3) + 
    ggtitle("Time series of monthly SPEI across regions")

ggsave(plot = heat, filename = "heatmap_SPEI3_grasslandssxregions_12_02_26.png", dpi = 300, width = 8, height = 4)


heat <- ggplot() + geom_tile(aes(y = factor(EP), x = m, fill = SPEI6_bin), data = ddf) + 
    scale_fill_brewer(name = "SPEI", na.value = 'grey75', palette = "RdYlGn", direction = 1) + 
    theme_grey(base_size = 10) + scale_x_date(date_breaks = "1 year", date_labels = "%Y",
        limits = c(min(ddf$m), max(ddf$m)), expand = c(0,0)) +
    xlab("Time") + ylab("EPs") + theme(axis.text.y = element_blank(),
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1, size = 4)) + 
    facet_wrap(factor(region)~., scales = "free_y", nrow = 3) + 
    ggtitle("Time series of monthly SPEI across regions")

ggsave(plot = heat, filename = "heatmap_SPEI6_grasslandsxregions_12_02_26.png", dpi = 300, width = 8, height = 4)


heat <- ggplot() + geom_tile(aes(y = factor(EP), x = m, fill = SPEI12_bin), data = ddf) + 
    scale_fill_brewer(name = "SPEI", na.value = 'grey75', palette = "RdYlGn", direction = 1) + 
    theme_grey(base_size = 10) + scale_x_date(date_breaks = "1 year", date_labels = "%Y",
        limits = c(min(ddf$m), max(ddf$m)), expand = c(0,0)) +
    xlab("Time") + ylab("EPs") + theme(axis.text.y = element_blank(),
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1, size = 4)) + 
    facet_wrap(factor(region)~., scales = "free_y", nrow = 3) + 
    ggtitle("Time series of monthly SPEI across regions")

ggsave(plot = heat, filename = "heatmap_SPEI12_grasslandsxregions_12_02_26.png", dpi = 300, width = 8, height = 4)

### ------------------------------------------------------------------------------------------------------------

### 16/02/26: Re-load SPEI tables for the grasslands and the forests. Compute mean N extreme drought month per EP
### for 1990-2006 and 2008-2024

setwd(extremes_dir)

### For grasslands
files <- dir()[grep("SPEI",dir())]
files <- files[grep("grasslands",files)]
files <- files[grep("_mw",files)] # files
res <- lapply(files, function(f) { d <- get(load(f)); return(d) })
ddf <- dplyr::bind_rows(res)
rm(res); gc()
# str(ddf); summary(ddf)

## Mean N of months of severe/extreme months per EP between 1990 and 2006
tally_base <- data.frame(
    ddf[ddf$m >= "1990-01-01" & ddf$m <= "2005-12-31",] %>%
    group_by(EP) %>%
    summarise(
        N = sum(SPEI6 <= -1.5)
    )
) # eo ddf
summary(tally_base); sd(tally_base$N)
# 7.147 ± 1.47

## Mean N of months of severe/extreme months per EP between 2008 and 2024
tally <- data.frame(
    ddf[ddf$m >= "2008-01-01",] %>%
    group_by(EP) %>%
    summarise(
        N = sum(SPEI6 <= -1.5)
    )
) # eo ddf
summary(tally); sd(tally$N)
# 31.66 ± 3.67

### -> 31.66/7.147 # > 4.43 times more drought months
### (31.66 - 7.147) / 7.147 # 342.9% increase

### Rbind and plot
tally_base$period <- factor("1990-2006")
tally$period <- factor("2008-2024")
t <- rbind(tally_base,tally)
# summary(t); str(t)
bplot <- ggplot(data = t, aes(x = period, y = N)) + geom_boxplot(fill = "grey") + xlab("") + ylab("N months of severe/extreme drought") + theme_minimal()
ggsave(plot = bplot, filename = "boxplot_N_1990-2006_vs_2008-2024_grasslands.jpg", dpi = 300, height = 4, width = 3)


### 01/06/26: Re-plotting SPEI6 heatmaps but from 2009 - BE20+WBF26 talks
### Define scPDSI bins for a nice looking and adequate colorbar
breaks <- c(-3,-2,-1.5,-1,-0.5,0.5,1,1.5,2,3) # breaks
# Give it it adequate labels too
labels <- c("< -2","-2 to -1.5","-1.5 to -1","-1 to -0.5","-0.5 to 0.5","0.5 to 1","1 to 1.5","1.5 to 2","> 2")
# Add bins to 'ddf' subset
ddf <- ddf[ddf$m >= "2009-01-01",]
ddf <- ddf %>% mutate(SPEI3_bin = cut(SPEI3, breaks = breaks, labels = labels, include.lowest = T))
ddf <- ddf %>% mutate(SPEI6_bin = cut(SPEI6, breaks = breaks, labels = labels, include.lowest = T))
ddf <- ddf %>% mutate(SPEI12_bin = cut(SPEI12, breaks = breaks, labels = labels, include.lowest = T))

# Re-order levels of the 'region' factor as follows: SCH > HND > SWA
ddf$region <- factor(ddf$region, levels = c("SCH","HND","SWA"))

heat <- ggplot() + geom_tile(aes(y = factor(EP), x = m, fill = SPEI3_bin), data = ddf) + 
    scale_fill_brewer(name = "SPEI", na.value = 'grey75', palette = "RdYlGn", direction = 1) + 
    theme_grey(base_size = 10) + scale_x_date(date_breaks = "1 year", date_labels = "%Y",
        limits = c(min(ddf$m),max(ddf$m)), expand = c(0,0)) +
    xlab("Time") + ylab("EPs") + theme(axis.text.y = element_blank(),
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1, size = 4)) + 
    facet_wrap(factor(region)~., scales = "free_y", nrow = 3) + 
    ggtitle("Time series of monthly SPEI across regions")

ggsave(plot = heat, filename = "heatmap_SPEI3_grasslandssxregions_>2009_01_06_26.png", dpi = 300, width = 8, height = 4)


heat <- ggplot() + geom_tile(aes(y = factor(EP), x = m, fill = SPEI6_bin), data = ddf) + 
    scale_fill_brewer(name = "SPEI", na.value = 'grey75', palette = "RdYlGn", direction = 1) + 
    theme_grey(base_size = 10) + scale_x_date(date_breaks = "1 year", date_labels = "%Y",
        limits = c(min(ddf$m), max(ddf$m)), expand = c(0,0)) +
    xlab("Time") + ylab("EPs") + theme(axis.text.y = element_blank(),
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1, size = 4)) + 
    facet_wrap(factor(region)~., scales = "free_y", nrow = 3) + 
    ggtitle("Time series of monthly SPEI across regions")

ggsave(plot = heat, filename = "heatmap_SPEI6_grasslandsxregions_>2009_01_06_26.png", dpi = 300, width = 8, height = 4)


heat <- ggplot() + geom_tile(aes(y = factor(EP), x = m, fill = SPEI12_bin), data = ddf) + 
    scale_fill_brewer(name = "SPEI", na.value = 'grey75', palette = "RdYlGn", direction = 1) + 
    theme_grey(base_size = 10) + scale_x_date(date_breaks = "1 year", date_labels = "%Y",
        limits = c(min(ddf$m), max(ddf$m)), expand = c(0,0)) +
    xlab("Time") + ylab("EPs") + theme(axis.text.y = element_blank(),
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1, size = 4)) + 
    facet_wrap(factor(region)~., scales = "free_y", nrow = 3) + 
    ggtitle("Time series of monthly SPEI across regions")

ggsave(plot = heat, filename = "heatmap_SPEI12_grasslandsxregions_>2009_01_06_26.png", dpi = 300, width = 8, height = 4)



### For forests
files <- dir()[grep("SPEI",dir())]
files <- files[grep("forests",files)]
files <- files[grep("_mw",files)] # files
res <- lapply(files, function(f) { d <- get(load(f)); return(d) })
ddf <- dplyr::bind_rows(res)
rm(res); gc()
# str(ddf); summary(ddf)

## Mean N of months of severe/extreme months per EP between 1990 and 2006
tally_base <- data.frame(
    ddf[ddf$m >= "1990-01-01" & ddf$m <= "2005-12-31",] %>%
    group_by(EP) %>%
    summarise(
        N = sum(SPEI6 <= -1.5)
    )
) # eo ddf
summary(tally_base); sd(tally_base$N, na.rm = TRUE)
# 7.076 ± 1.94


## Mean N of months of severe/extreme months per EP between 2008 and 2024
tally <- data.frame(
    ddf[ddf$m >= "2008-01-01",] %>%
    group_by(EP) %>%
    summarise(
        N = sum(SPEI6 <= -1.5)
    )
) # eo ddf
summary(tally); sd(tally$N, na.rm = TRUE)
# 26.72 ± 7.70

### -> 26.72/7.076 # > 3.77 time smore drought months
### (26.72 - 7.076) / 7.076 # 277.6% increase - LESS THAN IN GRASSLANDS

### Rbind and plot
tally_base$period <- factor("1990-2006")
tally$period <- factor("2008-2024")
t <- rbind(tally_base,tally)
# summary(t); str(t)
bplot <- ggplot(data = t, aes(x = period, y = N)) + geom_boxplot(fill = "grey") + xlab("") + ylab("N months of severe/extreme drought") + theme_minimal()
ggsave(plot = bplot, filename = "boxplot_N_1990-2006_vs_2008-2024_forests.jpg", dpi = 300, height = 4, width = 3)


### ------------------------------------------------------------------------------------------------------------

### 06/01/26: Re-load the SPEI & scPDSI tables and give an identifier to drought events. Basically, each events that
### are continuous in time (i.e., uninterrupted by a wet or normal period) should be given an identifier so we can track
### when systems are still ongoing a particular extreme event.

setwd(extremes_dir); dir()

### 1°) SPEI

# Load all files and make one panel of 12 Plots: 4 rows (QM) x 3 columns (regions)
files <- dir()[grep("SPEI",dir())]
files <- files[grep("_mw",files)] # files
res <- lapply(files, function(f) { d <- get(load(f)); return(d) })
spei <- dplyr::bind_rows(res)
rm(res); gc()
# summary(spei); str(spei)

### Add identifier with a scale-agnostic, reusable solution that:
# - Keeps event IDs separate
# - Preserves severity classes
# - Is safe for EP-level time series

# For testing FUN:
# df = spei
# spei_var = "SPEI3"
# scale_label = "SPEI3"

identify_spei_events <- function(df, spei_var, scale_label) {
  
    #' @param df: data frame containing SPEI time series
    #' @param spei_var: name of the SPEI column (character string, e.g. "SPEI3")
    #' @param scale_label: label used to tag event IDs (e.g. "SPEI3", "SPEI6")
    #' @return df: modified 'df' with the event IDs
    
    # Arrange to make sure EP x time ordering is adequate
    df <- df %>% arrange(EP,m) %>% group_by(EP) %>%
        mutate(
            spei_value = .data[[spei_var]], # Extract the selected SPEI variable in a generic way (.data[[...]] allows non-standard evaluation safely)
            spei_class = case_when(
                spei_value > 2            ~ "Extremely wet",
                spei_value > 1.5          ~ "Severely wet",
                spei_value > 1            ~ "Moderately wet",
                spei_value > 0.5          ~ "Mildly wet",
                spei_value >= -0.5 & spei_value <= 0.5 ~ "Normal",
                spei_value < -0.5 & spei_value >= -1   ~ "Mild drought",
                spei_value < -1   & spei_value >= -1.5 ~ "Moderate drought",
                spei_value < -1.5 & spei_value >= -2   ~ "Severe drought",
                spei_value < -2             ~ "Extreme drought",
                TRUE                        ~ NA_character_
            ), # Classify SPEI values into wet / normal / drought severity classes
            spei_event_type = case_when(
                spei_value < -0.5 ~ "drought",
                spei_value >  0.5 ~ "wet",
                TRUE              ~ "normal"
            ), # Reduce classes to a simple event type
            event_break = spei_event_type != lag(
                spei_event_type,
                default = first(spei_event_type)
            ),
            # Identify breaks between consecutive time steps
            # Assign a raw event ID by cumulatively summing breaks 
            event_id_raw = cumsum(event_break)
        ) %>%
        ungroup() %>%
        # Assign final drought & wet events identifiers
        mutate(
            event_id = case_when(
                spei_event_type == "drought" ~ paste0(EP, "_", scale_label, "_D_", event_id_raw),
                spei_event_type == "wet" ~ paste0(EP, "_", scale_label, "_W_", event_id_raw),
                spei_event_type == "normal" ~ "Normal"
            )
        ) # eo mutate
    
    # Return 
    df # str(df); data.frame(df[10000:10200,])

} # eo FUN - identify_spei_events

# Apply FUN to spei
df <- identify_spei_events(df = spei, spei_var = "SPEI6", scale_label = "SPEI6")
# summary(df); head(as.data.frame(df))

# Summarize
event_summary <- data.frame(
    df %>%
    filter(event_id != "Normal") %>% # Exclude normal periods explicitly
    group_by(event_id, EP, region, spei_event_type) %>% # 1 row per event
    summarise(
        start_date = min(m),
        end_date   = max(m),
        duration_months = n(),
        min_spei   = min(spei_value, na.rm = TRUE),
        mean_spei  = mean(spei_value, na.rm = TRUE),
        .groups = "drop"
    ) # eo summarise
) # eo ddf

# Check
summary(event_summary) # median duration = 3 months; mean duration = 6 months with SPEI6, increaes with SPEI12. SPEI12 gets closer to scPDSI
dim(event_summary)
str(event_summary)
event_summary[event_summary$duration_months >= 12,]
event_summary[event_summary$duration_months >= 15,]
dim(event_summary[event_summary$duration_months >= 12,]) # 1108 events longer than a year 


### 2°) scPDSI
files <- dir()[grep("scPDSI",dir())]
files <- files[grep("_mw",files)] # files
res <- lapply(files, function(f) { d <- get(load(f)); return(d) })
pdsi <- dplyr::bind_rows(res)
rm(res); gc()
# Add time bin as MonthxYear combination for the heatmap too
pdsi$Date <- lubridate::as_date(paste(pdsi$Month, pdsi$Year, sep = "/"), format = "%m/%Y")
# summary(pdsi); str(pdsi)


### Same as above for SPEI but for the following scPDSI categories:
# scPDSI values     Interpretation
#   > 4	            Extremely Wet
#   3 to 4          Severely Wet
#   2 to 3          Moderately Wet
#   1 to 2          Mildly Wet
#   -1 to 1         Normal
#   -1 to -2        Mild Drought
#   -2 to -3        Moderate Drought
#   -3 to -4        Severe Drought
#   < -4            Extreme Drought

### Writing identify_pdsi_events() 
df <- pdsi # for testing

identify_pdsi_events <- function(df) {
  
    #' @param df: data frame containing SPEI time series
    #' @return df: modified 'df' with the event IDs

    df <- df %>% arrange(EP,Date) %>% 
        group_by(EP) %>%
        mutate(
            pdsi_value = Value,
            pdsi_class = case_when(
                pdsi_value > 4 ~ "Extremely wet",
                pdsi_value >= 3 & pdsi_value <= 4 ~ "Severely wet",
                pdsi_value >= 2 & pdsi_value <  3 ~ "Moderately wet",
                pdsi_value >= 1 & pdsi_value <  2 ~ "Mildly wet",
                pdsi_value > -1 & pdsi_value <  1 ~ "Normal",
                pdsi_value <= -1 & pdsi_value > -2 ~ "Mild drought",
                pdsi_value <= -2 & pdsi_value > -3 ~ "Moderate drought",
                pdsi_value <= -3 & pdsi_value > -4 ~ "Severe drought",
                pdsi_value <= -4 ~ "Extreme drought",
                TRUE ~ NA_character_
            ),
            
            pdsi_event_type = case_when(
                pdsi_value <= -1 ~ "drought",
                pdsi_value >=  1 ~ "wet",
                TRUE ~ "normal"
            ),
      
            event_break  = pdsi_event_type != lag(pdsi_event_type,
                default = first(pdsi_event_type)
            ),
            
            event_id_raw = cumsum(event_break)
        ) %>%
        ungroup() %>%
        mutate(
            event_id = case_when(
                pdsi_event_type == "drought" ~
                paste0(EP, "_scPDSI_D_", event_id_raw),
                pdsi_event_type == "wet" ~
                paste0(EP, "_scPDSI_W_", event_id_raw),
                TRUE ~ "Normal"
            )
        ) # eo mutate

        # Return
        df

} # eo identify_pdsi_events

# Apply to 'pdsi'
df <- identify_pdsi_events(pdsi)
summary(data.frame(df))
head(data.frame(df))
data.frame(df)[130000:130100,]

# Summarize
pdsi_event_summary <- data.frame(
    df %>%
    filter(event_id != "Normal") %>%
    group_by(event_id, EP, region, pdsi_event_type) %>%
    summarise(
        start_date = min(Date),
        end_date = max(Date),
        duration_months = n(),
        min_pdsi  = min(pdsi_value, na.rm = TRUE),
        mean_pdsi = mean(pdsi_value, na.rm = TRUE),
        .groups = "drop"
    )
) # eo data.frame

summary(pdsi_event_summary) # median duration = 5, but max values and mean value are MUCH higher than with SPEI
head(pdsi_event_summary)
pdsi_event_summary[pdsi_event_summary$duration_months >= 100,]
dim(pdsi_event_summary[pdsi_event_summary$duration_months >= 100,]) # 53 events longer than 100 months, aka > 8 YEARS

### KEY TAKE AWAY: based on scPDSI, drought events are much MUCH longer than based on SPEI !! This is a 
### critical observation and it makes sense. scPDSI index is for identifying persistent regimes over very long scales.
### Meanwhile, the SPEI is meant for short to medium-term events and is better at evaluating the onset and termination
### of the events.

### By design, once scPDSI enters drought regime (< -1), it tends to stay there until sustained wet anomalies occur. 
### Meanwhile, SPEI has no "memory" as it just a standard anomaly based on accumulation windows (3/6/12 months). 
### A scPDSI drought lasting >100 months means: “The system never fully returned to a normal hydroclimatic balance for ~8+ years.”
### This is likely why studies do not use scPDSI to identify discrete drought events. 

# ✅ sc️ scPDSI is good for:
# Long-term drought background state
# Multi-year to decadal hydrological stress
# Legacy effects
# Groundwater / baseflow context
# Comparing climatic regimes

# ❌ scPDSI is NOT good for:
# Event-based resistance / recovery metrics
# Onset timing
# Short-term ecosystem responses
# Counting independent droughts

### -> Use SPEI 3/6/12
### SPEI6 is usually preferred over SPEI12 for drought event detection because it best balances responsiveness and persistence.
# Scale	    What it represents	                                    Memory
# SPEI 3	Short-term anomalies (meteorological / soil moisture)	Low
# SPEI 6	Seasonal to inter-seasonal drought stress	            Medium
# SPEI 12   Annual water balance	                                High

# SPEI 3: Captures short, sharp events; splits long droughts into multiple fragments; very sensitive to monthly variability; "sees monthly shocks"
# SPEI 6: Smooths short-term noise; events match ecosystem responses; widely used for ecological & hydrological drought events
# SPEI 12: Highly smoothed; merges consecutive short events; produces fewer but much longer events; behaves almost like scPDSI


### Summary report from Perplexity: 
## Prompt used: "I am evaluating various drought indices (namely: scPDSI and SPEI) that I am calculating
## based on observed long-term (1950-2024) monthly values of air temperature and precipitation for grasslands in Germany.
## I do not have evapotranspiration data, so I am computing SPEI based on proxies based on latitude
## (see the options available in the 'SPEI' R package). I computed SPEI based on three timescales:
## 3 months (SPEI3), 6 months (SPEI6) and 12 months (SPEI12). I think these are better than the scPDSI for my purposes.
## I want to combine SPEI values with annual vegetation records (species richness and biomass) to study how
## grassland diversity and productivity respond to drought and land-use intensity together (using metrics such as
## resistance, recovery, stability, etc.). I am wondering which SPEI timescale is best suited for my analyses.
## Can you please help me figure this out? Please examine the scientific peer-reviewed literature from the
## past 10 years (look specifically for studies that examined grasslands' resilience to drought;
## focus on studies published in journals published by Wiley) that used drought indices such as SPEI.
## Give me a summary of the indices used in the scientific literature, and please indicate their
## strengths and weaknesses. Please conclude by giving me clear recommendations as to how to proceed and
## how to choose between scPDSI and SPEI3/6/12."

# References:
# https://www.pnas.org/doi/10.1073/pnas.1207068110
# https://pmc.ncbi.nlm.nih.gov/articles/PMC9010421/ 
# https://pubmed.ncbi.nlm.nih.gov/39218106/ 
# https://www.sciencedirect.com/science/article/pii/S0378429023002344
# https://besjournals.onlinelibrary.wiley.com/doi/10.1111/1365-2745.14288

### -> SPEI-6 (6-month) is the optimal primary timescale for your grassland resilience study,
### supplemented by SPEI-3 (3-month) for assessing rapid physiological responses.
### scPDSI remains a valid alternative, but SPEI offers distinct advantages for vegetation-focused research.
### This recommendation is grounded in evidence from European grassland experiments, global meta-analyses,
### and methodological comparisons of drought indices published between 2013–2024.
### For a grassland vegetation study focused on annual species richness and biomass responses,
### SPEI is superior because: (i) your annual data collection aligns with SPEI's temporal flexibility,
### (ii) temperature effects on water stress are explicitly captured, and (iii) you can stratify responses
### by timescale to distinguish rapid physiological drought from accumulated water deficit effects.

### SPEI advantages for the study
# Proxy-based PET is acceptable: Your use of latitude-based PET from the SPEI R package follows established methodology in data-scarce regions
​# Temperature trend capture: German grasslands have warmed ~1.5°C since 1950;
# SPEI's explicit inclusion of temperature-driven evapotranspiration changes will reveal warming impacts on drought severity
​# Annual vegetation alignment: Your annual vegetation surveys (species richness, biomass) naturally align with SPEI's multi-timescale flexibility;
# SPEI-3 captures spring/early-summer stress, SPEI-6 captures accumulated stress through mid-growing season
# Established grassland literature: 60+ peer-reviewed grassland drought studies in the past 10 years use SPEI as the primary drought metric
# Policy relevance: EU Common Agricultural Policy and German environmental monitoring increasingly reference SPEI for drought assessment

### Include SPEI-3 (3-month timescale) to test:
# Whether rapid within-season drought stress (e.g., a dry May–July) has different resistance implications than cumulative 6-month water deficit
# Whether species richness responds differently to acute vs. chronic drought
# Whether land-use intensity modulates short-term (physiological) vs. long-term (community composition) drought responses differently

### Avoid using SPEI-12 as primary metric because grasslands are short-rooted;
### 12-month accumulated deficit conflates multiple growing seasons that your annual sampling cannot distinguish.

### While scPDSI is defensible, do not use scPDSI exclusively because its 7–10 month inherent timescale is misaligned with your annual vegetation surveys

### Conclusions:
### SPEI-6 should be the optimal primary choice for studying grassland diversity and productivity responses to drought and land-use intensity across
### the 1950–2024 dataset. This recommendation is grounded in:
#   (i) direct empirical validation in grassland systems (Bazzichetto et al., 2024; Stampfli et al., 2018; Vicente-Serrano et al., 2013);
#   (ii) methodological superiority for capturing seasonal water balance;
#   (iii) international standardization in agricultural/ecological drought assessment, and 
#   (iv) demonstrated ability to reveal land-use × drought interactions.

### scPDSI remains a defensible alternative and can serve as a complementary robustness check, but its single-timescale nature
### and agricultural-drought optimization make it less suitable as your primary metric for annual vegetation surveys.
### Include SPEI-3 as a sensitivity analysis to test whether short-term physiological drought reveals different insights than 
### 6-month accumulated deficit.
### By stratifying your analysis across SPEI-3, SPEI-6, and potentially SPEI-12, you will gain comprehensive understanding
### of how drought timescale, species traits, and land-use management interact to determine grassland resilience—an advance
### beyond single-index studies that has characterized the field until recently.

### ------------------------------------------------------------------------------------------------------------
### ------------------------------------------------------------------------------------------------------------
### ------------------------------------------------------------------------------------------------------------