### ------------------------------------------------------------------------------------------------------------

### 20/03/25 - ©Fabio Benedetti (Plant Ecology group, IPS, Uni Bern)

### R script to load the time series of hourly ERA5 Land data generated by Script#5.1 and use them to
### compute daily statistics (mean/min/max/CV)

### R script to: 
### - For every system, region, EP and variable available, load the hourly time series
###   (.Rdata files in /home/fbenedetti/ERA5-Land-DEU-processed/hourly/)
### - Compute daily mean/min/max/CV for each EP and climate variable
### - Beware: compute daily total precipitation (cumulative sum) instead of mean/min/max/CV 
### - Return as data.frame and save in /home/fbenedetti/ERA5-Land-DEU-processed/daily/

### NOTE: NO NEED TO PROCESS 'soil_temperature_level_3' because ERA5-Land soil temperature level 3
### refers to the temperature of the soil at a depth of 28-100 centimeters -> below BEO data

### Last update: 23/04/25 (Processing hourly 'volumetric_soil_water_layer_2')

### ------------------------------------------------------------------------------------------------------------

# Libraries
library("dplyr")
library("reshape2")
library("stringr")
library("lubridate")
library("parallel")

### ------------------------------------------------------------------------------------------------------------

### Write master FUN to compute the daily statistics
# To test FUN below while you're writing it
# file <- files[1]; file

compute_daily_stats <- function(file) {

        #' This function takes three arguments and returns a formatted data.frame:
        #' @param files the name of the .Rdata files containing the ERA5-Land hourly data (character)
        #' @return Prints the data.frame as .Rdata in the right dir
        
        setwd(paste("/home/fbenedetti/ERA5-Land-DEU-processed/hourly/",system,"/",region, sep = ""))

        d <- get(load(file))
        # dim(d); summary(d); str(d)

        # Convert POSIXct to Date
        d$date <- as.Date(d$time)

        # 07/04/25: Convert volumetric_soil_water_layer_1 and volumetric_soil_water_layer_1
        # to % so it matches our daily observations (SM_10 = % (percentage of volumetric water content))
        if( var %in% c("volumetric_soil_water_layer_1","volumetric_soil_water_layer_2") ) {
            d$value <- d$value*100
        } # eo if loop - volumetric_soil_water_layers

        # If var == total precipitation, compute daily total precipitation (sum)
        # If not, 
        if( var == "total_precipitation" ) {

            dd <- d %>% group_by(date) %>% summarize(total = sum(value, na.rm = T))
            
            # Add info
            dd$region <- unique(d$region)
            dd$system <- unique(d$system)
            dd$plot <- unique(d$plot)
            dd$var <- unique(d$var)
            dd$day <- lubridate::day(dd$date)
            dd$month <- lubridate::month(dd$date)
            dd$year <- lubridate::year(dd$date)
            # summary(dd); head(dd)

            # Re-order column
            dd <- dd[,c("region","system","plot","date","day","month","year","total")]

            # 27/03/25: Convert precipitation to mm so it matches our daily observations 
            dd$total <- (dd$total)*1000

        } else {

            dd <- d %>% 
                group_by(date) %>% 
                summarize( 
                    mean = mean(value, na.rm = T),
                    min = min(value, na.rm = T),
                    max = max(value, na.rm = T),
                    CV = (sd(value, na.rm = T)/mean)*100
            ) # eo clim
            
            # Add info
            dd$region <- unique(d$region)
            dd$system <- unique(d$system)
            dd$plot <- unique(d$plot)
            dd$var <- unique(d$var)
            dd$day <- lubridate::day(dd$date)
            dd$month <- lubridate::month(dd$date)
            dd$year <- lubridate::year(dd$date)
            # summary(dd); head(dd); str(dd)

            # Re-order column
            dd <- dd[,c("region","system","plot","date","day","month","year","mean","min","max","CV")]

        } # eo if else loop - var

        # Save
        message(paste("Saving the daily stats of ",var," measurements for the ",system," of the ",region,"\n", sep = ""))
        setwd(paste("/home/fbenedetti/ERA5-Land-DEU-processed/daily/",system,"/",region,"/", sep = ""))
        save(x = dd, file = paste("table_daily_ERA5-Land_data_",var,"_",unique(dd$plot),".Rdata", sep = ""))

        # Clean and stuff
        rm(dd,d); gc()

} # eo FUN - compute_daily_stats


### To compute daily stats on all EPs using compute_daily_stats() above
compute_daily_stats_all <- function(var, system, region, mc) {

        #' This function takes three arguments and returns a formatted data.frame:
        #' @param var the climate variable to process (character) - one of the following: 
        #' 2m_temperature, skin_temperature, soil_temperature_level_1, soil_temperature_level_2, 
        #' soil_temperature_level_3, total_precipitation, volumetric_soil_water_layer_1,
        #' volumetric_soil_water_layer_2, evaporation_from_vegetation_transpiration 
        #' @param system System name (character): 'grassland' or 'forest'
        #' @param region Region name (character): 'SCH' or 'HND' or 'SWA'
        #' @param mc Number of CPUs to parallel on (numeric)
        #' @return A formatted data.frame combining the daily statistics

        message(paste("Computing the daily stats of ",var," measurements for the ",system," of the ",region,  sep = ""))

        setwd(paste("/home/fbenedetti/ERA5-Land-DEU-processed/hourly/",system,"/",region,"/", sep = ""))
        # identify the files associated to the variable you are processing
        files <- dir()[grepl(var,dir())] # files; should be of length 50 because 50 EPs per systemxregion combination
        
        if( length(files) != 50 ) {
            stop( paste("Less than 50 files; Check that you have hourly data for all 50 EPs?", sep = "") )
        } # eo if else loop 

        # In a lapply, call compute_daily_stats() defined above and return daily stats
        require("parallel")
        mclapply(X = files, FUN = compute_daily_stats, mc.cores = mc) # eo mclapply

        # Go back to dir
        setwd(paste("/home/fbenedetti/ERA5-Land-DEU-processed/", sep = ""))

} # eo FUN - compute_daily_stats_all

# 24/03/25: Test compute_daily_stats_all() above
# compute_daily_stats_all(var = "2m_temperature", system = "grassland", region = "SWA", mc = 25)
# Somehow need to manually input the arguments before re-running the FUN?

var <- "volumetric_soil_water_layer_2"

for(system in c("grassland","forest")) {
    for(region in c('HND','SCH','SWA')) {
        compute_daily_stats_all(var, system, region, mc = 30)
    } # eo for loop 2
} # eo for loop 1

### ------------------------------------------------------------------------------------------------------------
### ------------------------------------------------------------------------------------------------------------
### ------------------------------------------------------------------------------------------------------------
